kind: Service
apiVersion: v1
metadata:
  name: train-schedule-canary
spec:
  type: NodePort
  selector:
    app: train-schedule-canary
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-canary
  labels:
    app: train-schedule-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-canary
      track: stable
  template:
    metadata:
      labels:
        app: train-schedule-canary
        track: stable
    spec:
      containers:
      - name: train-schedule-canary
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
